### ISSUE TITLE
Issues_with_the_simulations_on_open-edx

### ISSUE THREAD

**Issue by sravanthimodepu** [vlead/iiith-labs-testing-and-fixing#1] opened 2017-06-12 05:38 UTC
Experiments are not visible in small screen, but visible on full screen. In few machines the simulator is visible even in small screen where as in few machines not. Found Discrepancy.

**Comment by BSravanthi** [comment] 2018-09-04 06:50
Closed as the issue is no longer existed

**Closed as completed by BSravanthi** 2018-09-04 06:50 UTC
