### ISSUE TITLE
Issue_with_bread_crumb_overlaps_bookmark_button_on_Openedx

### ISSUE THREAD

**Issue by sravanthimodepu** [vlead/iiith-labs-testing-and-fixing#3] opened 2017-06-12 05:40 UTC
In Introduction and Theory & Further readings sections in all the experiments of Analog CMOS VLSI Design Circuit lab, the bread crumb is overlapping the bookmarks button.This is the issue with Open-edx.

**Comment by BSravanthi** [comment] 2018-09-04 06:49
Closed as the issue is no longer existed

**Closed as completed by BSravanthi** 2018-09-04 06:49 UTC
