### ISSUE TITLE
Issue_with_special_characters_in_the_quiz_on_openedx

### ISSUE THREAD

**Issue by sravanthimodepu** [vlead/iiith-labs-testing-and-fixing#2] opened 2017-06-12 05:38 UTC
If there are some special characters and a piece of code in the quiz section, we are Unable to export the questions to the open-edx. Due to this, there is no quiz section for some of the experiments.

**Comment by BSravanthi** [comment] 2018-09-04 06:49
Closed as the issue is no longer existed

**Closed as completed by BSravanthi** 2018-09-04 06:49 UTC
